# Generated by Django 4.2.6 on 2023-11-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del cliente'),
        ),
    ]
